VOCABULARY = {
"bonjour": {url:"https://www.elix-lsf.fr/IMG/mp4/bonjour-3.mp4"},
"au revoir": {url:"https://www.elix-lsf.fr/IMG/mp4/aurevoir_nm_1_1.mp4"},
"comment ça va ?": {url:"https://www.elix-lsf.fr/IMG/mp4/cava_int_10_6-3.mp4"},
"être en forme": {url:"https://www.elix-lsf.fr/IMG/mp4/enforme_adj_1_2.mp4"},
"oui": {url:"https://www.elix-lsf.fr/IMG/mp4/oui_adv_1_1.mp4"},
"non": {url:"https://www.elix-lsf.fr/IMG/mp4/non_adv_1_1.mp4"},
"pause": {url:"https://www.elix-lsf.fr/IMG/mp4/pause.mp4"},
"café": {url:"https://www.elix-lsf.fr/IMG/mp4/cafe_nm_1_6.mp4"},
"thé": {url:"https://www.elix-lsf.fr/IMG/mp4/the.mp4"},
"être en retard": {url:"https://www.elix-lsf.fr/IMG/mp4/retard2.mp4"},
"être fatigué": {url:"https://www.elix-lsf.fr/IMG/mp4/fatigue_adj_1_6.mp4"},
"être malade": {url:"https://www.elix-lsf.fr/IMG/mp4/malade-3.mp4"},
"s'il vous plaît": {url:"https://www.elix-lsf.fr/IMG/mp4/02252.mp4"},
"pardon": {url:"https://www.elix-lsf.fr/IMG/mp4/pardon_nm_1_1.mp4"},
"merci": {url:"https://www.elix-lsf.fr/IMG/mp4/merci_nm_1_1-2.mp4"},
"toilettes": {url:"https://www.elix-lsf.fr/IMG/mp4/toilettes_n_1_6.mp4"},
"sourd": {url:"https://www.elix-lsf.fr/IMG/mp4/sourd.mp4"},
"boisson": {url:"https://www.elix-lsf.fr/IMG/mp4/boisson_nf_1_1.mp4"},
"couleur": {url:"https://www.elix-lsf.fr/IMG/mp4/couleur.mp4"},
"bleu": {url:"https://www.elix-lsf.fr/IMG/mp4/bleu_nm_1_11.mp4"},
"rouge": {url:"https://www.elix-lsf.fr/IMG/mp4/rouge.mp4"},
"vert": {url:"https://www.elix-lsf.fr/IMG/mp4/vert.mp4"},
"jaune": {url:"https://www.elix-lsf.fr/IMG/mp4/jaune_adj_1_1.mp4"},
"gris": {url:"https://www.elix-lsf.fr/IMG/mp4/gris_nm_1_2.mp4"},
"rose": {url:"https://www.elix-lsf.fr/IMG/mp4/rose_adj_2_1.mp4"},
"noir": {url:"https://www.elix-lsf.fr/IMG/mp4/01488.mp4"},
"blanc": {url:"https://www.elix-lsf.fr/IMG/mp4/blanc_adj_1_1.mp4"},
"violet": {url:"https://www.elix-lsf.fr/IMG/mp4/01478.mp4"},
"marron": {url:"https://www.elix-lsf.fr/IMG/mp4/marron_adjetn_10_1.mp4"},
"orange": {url:"https://www.elix-lsf.fr/IMG/mp4/orange_adj_1_2.mp4"},
"or (métal)": {url:"https://www.elix-lsf.fr/IMG/mp4/or_nm_1_1.mp4"},
"argent (métal)": {url:"https://www.elix-lsf.fr/IMG/mp4/argent_nm_1_1.mp4"},
"clair": {url:"https://www.elix-lsf.fr/IMG/mp4/clair_adj_1_1.mp4"},
"foncé": {url:"https://www.elix-lsf.fr/IMG/mp4/fonce_adj_1_1.mp4"},
"vif": {url:"https://www.elix-lsf.fr/IMG/mp4/vif_adj_1_1.mp4"},
"transparent": {url:"https://www.elix-lsf.fr/IMG/mp4/transparent_adj_1_2.mp4"},
"manger": {url:"https://www.elix-lsf.fr/IMG/mp4/00280.mp4"},
"boire": {url:"https://www.elix-lsf.fr/IMG/mp4/boire-2.mp4"},
"voiture": {url:"https://www.elix-lsf.fr/IMG/mp4/voiture_nf_1_6.mp4"},
"eau": {url:"https://www.elix-lsf.fr/IMG/mp4/eau-2.mp4"},
"grand": {url:"https://www.elix-lsf.fr/IMG/mp4/grand_adj_1_1.mp4"},
"moto": {url:"https://www.elix-lsf.fr/IMG/mp4/moto_nf_1_1.mp4"},
"vélo": {url:"https://www.elix-lsf.fr/IMG/mp4/velo-2.mp4"},
"aspirateur": {url:"https://www.elix-lsf.fr/IMG/mp4/aspirateur.mp4"},
"arbre": {url:"https://www.elix-lsf.fr/IMG/mp4/arbre-3.mp4"},
"bébé": {url:"https://www.elix-lsf.fr/IMG/mp4/bebe_nm_1_2.mp4"},
"oeil": {url:"https://www.elix-lsf.fr/IMG/mp4/oeil_nm_1_1.mp4"},
"bouche": {url:"https://www.elix-lsf.fr/IMG/mp4/bouche_nf_1_1.mp4"},
"nez": {url:"https://www.elix-lsf.fr/IMG/mp4/nez_nm_1_1.mp4"},
"oreille": {url:"https://www.elix-lsf.fr/IMG/mp4/oreille_nf_1_1.mp4"},
"cheveu": {url:"https://www.elix-lsf.fr/IMG/mp4/cheveu_nm_1_1.mp4"},
"lampe torche": {url:"https://www.elix-lsf.fr/IMG/mp4/lampedepoche_nf_10_1.mp4"},
"bouteille": {url:"https://www.elix-lsf.fr/IMG/mp4/bouteille_nf_1_1.mp4"},
"parapluie": {url:"https://www.elix-lsf.fr/IMG/mp4/parapluie_nm_1_1.mp4"},
"peur": {url:"https://www.elix-lsf.fr/IMG/mp4/peur.mp4"},
"faim": {url:"https://www.elix-lsf.fr/IMG/mp4/00167.mp4"},
"soif": {url:"https://www.elix-lsf.fr/IMG/mp4/soif_nf_1_1.mp4"},
"école": {url:"https://www.elix-lsf.fr/IMG/mp4/ecole-4.mp4"},
"sac à dos": {url:"https://www.elix-lsf.fr/IMG/mp4/sacados_nm_1_1.mp4"},
"pêcher (à la ligne)": {url:"https://www.elix-lsf.fr/IMG/mp4/pecher_1_2.mp4"},
"fleur": {url:"https://www.elix-lsf.fr/IMG/mp4/fleur_nf_1_1.mp4"},
"aimer": {url:"https://www.elix-lsf.fr/IMG/mp4/aimer_v_2_6.mp4"},
"détester": {url:"https://www.elix-lsf.fr/IMG/mp4/detester_v_1_1.mp4"},
"ne pas aimer": {url:"https://www.elix-lsf.fr/IMG/mp4/nepasaimer_v_10_6.mp4"},
"réfrigérateur": {url:"https://www.elix-lsf.fr/IMG/mp4/refrigerateur_nm_1_1.mp4"},
"congélateur": {url:"https://www.elix-lsf.fr/IMG/mp4/congelateur_nm_1_1.mp4"},
"table": {url:"https://www.elix-lsf.fr/IMG/mp4/table_nf_1_1.mp4"},
"siège": {url:"https://www.elix-lsf.fr/IMG/mp4/00018.mp4"},
"livre": {url:"https://www.elix-lsf.fr/IMG/mp4/livre.mp4"},
"monnaie/argent": {url:"https://www.elix-lsf.fr/IMG/mp4/argent-2.mp4"},
"indien d'Amérique": {url:"https://www.elix-lsf.fr/IMG/mp4/00248.mp4"},
"vache": {url:"https://www.elix-lsf.fr/IMG/mp4/vache_nf_1_6.mp4"},
"taureau": {url:"https://www.elix-lsf.fr/IMG/mp4/taureau_nm_1_1.mp4"},
"éléphant": {url:"https://www.elix-lsf.fr/IMG/mp4/00161.mp4"},
"boiter": {url:"https://www.elix-lsf.fr/IMG/mp4/boiter_v_1_1.mp4"},
"chat": {url:"https://www.elix-lsf.fr/IMG/mp4/chat-2.mp4"},
"homme": {url:"https://www.elix-lsf.fr/IMG/mp4/homme-2.mp4"},
"femme": {url:"https://www.elix-lsf.fr/IMG/mp4/femme-2.mp4"},
"fille": {url:"https://www.elix-lsf.fr/IMG/mp4/fille.mp4"},
"garçon": {url:"https://www.elix-lsf.fr/IMG/mp4/garcon.mp4"},
"jeune": {url:"https://www.elix-lsf.fr/IMG/mp4/jeune_adj_1_1.mp4"},
"vieux": {url:"https://www.elix-lsf.fr/IMG/mp4/vieux_adj_2_1.mp4"},
"mince": {url:"https://www.elix-lsf.fr/IMG/mp4/mince_adj_1_1.mp4"},
"gros": {url:"https://www.elix-lsf.fr/IMG/mp4/gros_adj_1_1.mp4"},
"visage": {url:"https://www.elix-lsf.fr/IMG/mp4/visage_nm_1_1.mp4"},
"langue": {url:"https://www.elix-lsf.fr/IMG/mp4/langue_nf_2_1.mp4"},
"sourcil": {url:"https://www.elix-lsf.fr/IMG/mp4/soucils.mp4"},
"cils": {url:"https://www.elix-lsf.fr/IMG/mp4/cil_nm_1_1.mp4"},
"accueil": {url:"https://www.elix-lsf.fr/IMG/mp4/accueil_nm_2_1.mp4"},
"scie": {url:"https://www.elix-lsf.fr/IMG/mp4/scie_nf_1_1.mp4"},
"sucette": {url:"https://www.elix-lsf.fr/IMG/mp4/sucette_nf_1_1.mp4"},
"glace": {url:"https://www.elix-lsf.fr/IMG/mp4/glace_nf_2_1.mp4"},
"loupe": {url:"https://www.elix-lsf.fr/IMG/mp4/loupe_nf_2_1.mp4"},
"bowling": {url:"https://www.elix-lsf.fr/IMG/mp4/bowling_nm_1_1.mp4"},
"lunettes": {url:"https://www.elix-lsf.fr/IMG/mp4/lunettes_nfp_1_1.mp4"},
"scooter": {url:"https://www.elix-lsf.fr/IMG/mp4/scooter_nm_1_6.mp4"},
"question": {url:"https://www.elix-lsf.fr/IMG/mp4/question_nf_1_1.mp4"},
"corps": {url:"https://www.elix-lsf.fr/IMG/mp4/corps_nm_1_1.mp4"},
"enceinte": {url:"https://www.elix-lsf.fr/IMG/mp4/enceinte_adj_1_1.mp4"},
"signe": {url:"https://www.elix-lsf.fr/IMG/mp4/signe_nm_2_2.mp4"},
"lèvre": {url:"https://www.elix-lsf.fr/IMG/mp4/levre_nf_1_1.mp4"},
"avant": {url:"https://www.elix-lsf.fr/IMG/mp4/avant_adv_1_1_-_copie.mp4"},
"après": {url:"https://www.elix-lsf.fr/IMG/mp4/apres_adv_1_1.mp4"},
"partir": {url:"https://www.elix-lsf.fr/IMG/mp4/partir_v_3_6.mp4"},
"compris": {url:"https://www.elix-lsf.fr/IMG/mp4/compris_adj_2_1.mp4"},
"forme": {url:"https://www.elix-lsf.fr/IMG/mp4/forme_nf_1_1.mp4"},
"beau": {url:"https://www.elix-lsf.fr/IMG/mp4/beau.mp4"},
"moche": {url:"https://www.elix-lsf.fr/IMG/mp4/moche.mp4"},
"pareil": {url:"https://www.elix-lsf.fr/IMG/mp4/pareil_adj_1_1.mp4"},
"différent": {url:"https://www.elix-lsf.fr/IMG/mp4/different_adj_1_2.mp4"},
"interdit": {url:"https://www.elix-lsf.fr/IMG/mp4/interdit.mp4"},
"hache": {url:"https://www.elix-lsf.fr/IMG/mp4/hache_nf_1_1.mp4"},
"maison": {url:"https://www.elix-lsf.fr/IMG/mp4/maison-2.mp4"},
"sous-titre": {url:"https://www.elix-lsf.fr/IMG/mp4/sous-titrer_v_1_6.mp4"},
"télévision": {url:"https://www.elix-lsf.fr/IMG/mp4/television_nf_1_6.mp4"},
"traducteur": {url:"https://www.elix-lsf.fr/IMG/mp4/traducteur_nm_1_6.mp4"},
"peindre": {url:"https://www.elix-lsf.fr/IMG/mp4/peindre_v_2_1.mp4"},
"affiche": {url:"https://www.elix-lsf.fr/IMG/mp4/affiche_nf_1_1.mp4"},
"dessiner": {url:"https://www.elix-lsf.fr/IMG/mp4/dessiner_v_1_1.mp4"},
"écrire": {url:"https://www.elix-lsf.fr/IMG/mp4/ecrire_v_1_1.mp4"},
"lentille de contact": {url:"https://www.elix-lsf.fr/IMG/mp4/lentille_nf_5_6.mp4"},
"énerver": {url:"https://www.elix-lsf.fr/IMG/mp4/enerver_v_1_1.mp4"},
"personne folle": {url:"folle https://www.elix-lsf.fr/IMG/mp4/fou_nm_1_1.mp4"},
"avion": {url:"https://www.elix-lsf.fr/IMG/mp4/avion_nm_1_1.mp4"},
"bateau": {url:"https://www.elix-lsf.fr/IMG/mp4/bateau_nm_1_1.mp4"},
"mer": {url:"https://www.elix-lsf.fr/IMG/mp4/mer_nf_2_1.mp4"},
"ciel": {url:"https://www.elix-lsf.fr/IMG/mp4/ciel_nm_1_1.mp4"},
"pluie": {url:"https://www.elix-lsf.fr/IMG/mp4/pluie-2.mp4"},
"douche": {url:"https://www.elix-lsf.fr/IMG/mp4/douche_nf_1_1.mp4"},
"guitare": {url:"https://www.elix-lsf.fr/IMG/mp4/guitare_nf_1_1.mp4"},
"violon": {url:"https://www.elix-lsf.fr/IMG/mp4/violon_nm_1_1.mp4"},
"travail": {url:"https://www.elix-lsf.fr/IMG/mp4/travail-2.mp4"},
"quel": {url:"https://www.elix-lsf.fr/IMG/mp4/quel_adj_1_1.mp4"},
"dentifrice": {url:"https://www.elix-lsf.fr/IMG/mp4/dentifrice_nm_1_6.mp4"},
"révision": {url:"https://www.elix-lsf.fr/IMG/mp4/revision_nf_1_1.mp4"},
"musique": {url:"https://www.elix-lsf.fr/IMG/mp4/musique_nf_2_6.mp4"},
"moustache": {url:"https://www.elix-lsf.fr/IMG/mp4/moustache_nf_2_1.mp4"},
"barbe": {url:"https://www.elix-lsf.fr/IMG/mp4/barbe_nf_1_1.mp4"},
"rasoir": {url:"https://www.elix-lsf.fr/IMG/mp4/00340.mp4"},
"noir (de peau)": {url:"https://www.elix-lsf.fr/IMG/mp4/noir_nprop_1_6.mp4"},
"la joue": {url:"https://www.elix-lsf.fr/IMG/mp4/joue_nf_1_1.mp4"},
"Etats-unis": {url:"https://www.elix-lsf.fr/IMG/mp4/etats-unis_nprop_1_6.mp4"},
"bravo": {url:"https://www.elix-lsf.fr/IMG/mp4/00074-4.mp4"},
"France": {url:"https://www.elix-lsf.fr/IMG/mp4/france_nprop_10_6.mp4"},
"front": {url:"https://www.elix-lsf.fr/IMG/mp4/00220.mp4"},
"théâtre": {url:"https://www.elix-lsf.fr/IMG/mp4/theatre_nm_1_1.mp4"},
"comédien": {url:"https://www.elix-lsf.fr/IMG/mp4/comedien_n_1_1_copie.mp4"},
"président": {url:"https://www.elix-lsf.fr/IMG/mp4/00039-2.mp4"},
"république": {url:"https://www.elix-lsf.fr/IMG/mp4/republique_nf_1_1.mp4"},
"policier": {url:"https://www.elix-lsf.fr/IMG/mp4/00005.mp4"},
"mort": {url:"https://www.elix-lsf.fr/IMG/mp4/mort_adj_2_1.mp4"},
"vivant": {url:"https://www.elix-lsf.fr/IMG/mp4/vivant_adj_2_1.mp4"},
"film": {url:"https://www.elix-lsf.fr/IMG/mp4/film_nm_2_1.mp4"},
"chant": {url:"https://www.elix-lsf.fr/IMG/mp4/chant_nm_1_6-2.mp4"},
"chantsigne": {url:"https://www.elix-lsf.fr/IMG/mp4/00862.mp4"},
"danse": {url:"https://www.elix-lsf.fr/IMG/mp4/danse_nf_2_6-3.mp4"},
"musclé": {url:"https://www.elix-lsf.fr/IMG/mp4/muscle_adj_1_1.mp4"},
"couronne": {url:"https://www.elix-lsf.fr/IMG/mp4/couronne_nf_1_2.mp4"},
"roi": {url:"https://www.elix-lsf.fr/IMG/mp4/roi_nm_1_1.mp4"},
"prince": {url:"https://www.elix-lsf.fr/IMG/mp4/prince_nm_1_1.mp4"},
"caméscope/caméra": {url:"https://www.elix-lsf.fr/IMG/mp4/camescope_nm_1_1.mp4"},
"famille": {url:"https://www.elix-lsf.fr/IMG/mp4/famille_nf_1_1.mp4"},
"grand-mère": {url:"https://www.elix-lsf.fr/IMG/mp4/grand_mere.mp4"},
"grand-père": {url:"https://www.elix-lsf.fr/IMG/mp4/grand-pere_nm_1_6.mp4"},
"mère": {url:"https://www.elix-lsf.fr/IMG/mp4/00253-2.mp4"},
"père": {url:"https://www.elix-lsf.fr/IMG/mp4/pere_nm_1_1.mp4"},
"soeur": {url:"https://www.elix-lsf.fr/IMG/mp4/soeur_nf_2_1.mp4"},
"frère": {url:"https://www.elix-lsf.fr/IMG/mp4/frere_nm_1_1.mp4"},
"fils": {url:"https://www.elix-lsf.fr/IMG/mp4/fils_nm_1_1.mp4"},
"petit-fils": {url:"https://www.elix-lsf.fr/IMG/mp4/petit-fils_nm_1_6.mp4"},
"neveu/nièce": {url:"https://www.elix-lsf.fr/IMG/mp4/neveu_nm_1_1.mp4"},
"cousin/cousine": {url:"https://www.elix-lsf.fr/IMG/mp4/cousin_nm_2_1.mp4"},
"tante": {url:"https://www.elix-lsf.fr/IMG/mp4/tante_nf_1_6.mp4"},
"oncle": {url:"https://www.elix-lsf.fr/IMG/mp4/oncle_nm_1_2.mp4"},
"couple": {url:"https://www.elix-lsf.fr/IMG/mp4/couple_nm_1_1.mp4"},
"petit(e) ami(e)": {url:"https://www.elix-lsf.fr/IMG/mp4/00265.mp4"},
"ami": {url:"https://www.elix-lsf.fr/IMG/mp4/ami.mp4"},
"fiancer": {url:"https://www.elix-lsf.fr/IMG/mp4/fiancer_v_1_1.mp4"},
"divorce": {url:"https://www.elix-lsf.fr/IMG/mp4/divorce_nm_1_2.mp4"},
"demi-frère": {url:"https://www.elix-lsf.fr/IMG/mp4/00245-2.mp4"},
"montagne": {url:"https://www.elix-lsf.fr/IMG/mp4/montagne_nf_1_2.mp4"},
"campagne": {url:"https://www.elix-lsf.fr/IMG/mp4/campagne_nf_1_1.mp4"},
"camping": {url:"https://www.elix-lsf.fr/IMG/mp4/camping_nm_1_1.mp4"},
"marier": {url:"https://www.elix-lsf.fr/IMG/mp4/marier_v_1_1.mp4"},
"amour": {url:"https://www.elix-lsf.fr/IMG/mp4/amour_nm_1_1.mp4"},
"cheveux bouclés": {url:"https://www.elix-lsf.fr/IMG/mp4/boucle_adj_2_6.mp4"},
"grands-parents":{url:"https://www.elix-lsf.fr/IMG/mp4/grands-parents_nmp_1_1.mp4"},
"parents":{url:"https://www.elix-lsf.fr/IMG/mp4/parents_nmp_3_1.mp4"},
"enfants":{url:"https://www.elix-lsf.fr/IMG/mp4/enfant-2.mp4"},
"célibataire":{url:"https://www.elix-lsf.fr/IMG/mp4/celibataire_adj_1_1.mp4"},
"beau-fils":{url:"https://www.elix-lsf.fr/IMG/mp4/beau-fils_nm_1_1.mp4"},
"belle-fille":{url:"https://www.elix-lsf.fr/IMG/mp4/belle-fille_nf_1_6.mp4"},
"beau-père":{url:"https://www.elix-lsf.fr/IMG/mp4/00260-2.mp4"},
"belle-mère":{url:"https://www.elix-lsf.fr/IMG/mp4/00249-2.mp4"},
"arrière grands parents":{url:"https://www.elix-lsf.fr/IMG/mp4/arriere-grand-parent_nm_1_6.mp4"},
"gay":{url:"https://www.elix-lsf.fr/IMG/mp4/00102-4.mp4"},
"lesbienne":{url:"https://www.elix-lsf.fr/IMG/mp4/00104-2.mp4"},
"amant":{url:"https://www.elix-lsf.fr/IMG/mp4/amant_nm_1_1.mp4"},
"sapin":{url:"https://www.elix-lsf.fr/IMG/mp4/sapin_nm_1_1.mp4"},
"dieu":{url:"https://www.elix-lsf.fr/IMG/mp4/dieu_nm_1_6.mp4"},
"capricieux":{url:"https://www.elix-lsf.fr/IMG/mp4/capricieux_adj_1_2.mp4"},
"canapé":{url:"https://www.elix-lsf.fr/IMG/mp4/canape_nm_1_1.mp4"},
"balai":{url:"https://www.elix-lsf.fr/IMG/mp4/balai_nm_1_1.mp4"},
"bâiller":{url:"https://www.elix-lsf.fr/IMG/mp4/bailler_v_1_3.mp4"},
"skier":{url:"https://www.elix-lsf.fr/IMG/mp4/skier_v_1_6.mp4"},
"thermomètre":{url:"https://www.elix-lsf.fr/IMG/mp4/thermometremedical_nm_1_6.mp4"},
"sandwich":{url:"https://www.elix-lsf.fr/IMG/mp4/sandwich_nm_1_1.mp4"},
"hamburger":{url:"https://www.elix-lsf.fr/IMG/mp4/hamburger_nm_1_1.mp4"},
"radin":{url:"https://www.elix-lsf.fr/IMG/mp4/radin_adj_1_1.mp4"},
"sèche cheveux ":{url:"https://www.elix-lsf.fr/IMG/mp4/seche-cheveux_nm_1_1.mp4"},
"repasser (le linge)":{url:"https://www.elix-lsf.fr/IMG/mp4/repasser_v_5_1.mp4"},
"flûte":{url:"https://www.elix-lsf.fr/IMG/mp4/flute_nf_1_2.mp4"},
"trompette":{url:"https://www.elix-lsf.fr/IMG/mp4/trompette_nf_1_1.mp4"},
"ronfler":{url:"https://www.elix-lsf.fr/IMG/mp4/ronfler_v_1_1.mp4"},
"carnet":{url:"https://www.elix-lsf.fr/IMG/mp4/carnet_nm_1_1.mp4"},
"carte à jouer":{url:"https://www.elix-lsf.fr/IMG/mp4/carte_nf_2_6.mp4"},
"serrure":{url:"https://www.elix-lsf.fr/IMG/mp4/serrure_nf_1_1.mp4"},
"clé":{url:"https://www.elix-lsf.fr/IMG/mp4/cle_nf_10_6.mp4"},
"savon":{url:"https://www.elix-lsf.fr/IMG/mp4/savon.mp4"},
"photo":{url:"https://www.elix-lsf.fr/IMG/mp4/photo.mp4"},
"image":{url:"https://www.elix-lsf.fr/IMG/mp4/image_nf_3_1.mp4"},
"puer":{url:"https://www.elix-lsf.fr/IMG/mp4/puer_v_1_1.mp4"},
"terminer":{url:"https://www.elix-lsf.fr/IMG/mp4/terminer_v_1_6.mp4"},
"exemple":{url:"https://www.elix-lsf.fr/IMG/mp4/exemple.mp4"},
"maigre":{url:"https://www.elix-lsf.fr/IMG/mp4/maigre_adj_1_1.mp4"},
"fesses":{url:"https://www.elix-lsf.fr/IMG/mp4/fesses_nfp_1_1.mp4"},
"chauve":{url:"https://www.elix-lsf.fr/IMG/mp4/chauve_nm_1_1.mp4"},
"couettes":{url:"https://www.elix-lsf.fr/IMG/mp4/couette_nf_2_1.mp4"},
"blond":{url:"https://www.elix-lsf.fr/IMG/mp4/blond_nm_1_6.mp4"},
"roux (cheveux)":{url:"https://www.elix-lsf.fr/IMG/mp4/roux_adj_2_1.mp4"},
"brun":{url:"https://www.elix-lsf.fr/IMG/mp4/brun_adj_1_1.mp4"},
"narine":{url:"https://www.elix-lsf.fr/IMG/mp4/narine_nf_1_1.mp4"},
"fossette":{url:"https://www.elix-lsf.fr/IMG/mp4/fossette_nf_1_1.mp4"},
"facile":{url:"https://www.elix-lsf.fr/IMG/mp4/facile.mp4"},
"difficile":{url:"https://www.elix-lsf.fr/IMG/mp4/difficile1.mp4"},
"cinéma":{url:"https://www.elix-lsf.fr/IMG/mp4/cinema_nm_1_2.mp4"},
"laid":{url:"https://www.elix-lsf.fr/IMG/mp4/laid_adj_3_1.mp4"},
"football":{url:"https://www.elix-lsf.fr/IMG/mp4/football-2.mp4"},
"ville":{url:"https://www.elix-lsf.fr/IMG/mp4/ville_nf_1_1.mp4"},
"arabe":{url:"https://www.elix-lsf.fr/IMG/mp4/arabe_adj_1_1.mp4"},
"rap":{url:"https://www.elix-lsf.fr/IMG/mp4/00864.mp4"},
"métis":{url:"https://www.elix-lsf.fr/IMG/mp4/metis_adj_1_2.mp4"},
"fusée":{url:"https://www.elix-lsf.fr/IMG/mp4/fusee_nf_1_1.mp4"},
"vacances":{url:"https://www.elix-lsf.fr/IMG/mp4/vacances-2.mp4"},
"oublier":{url:"https://www.elix-lsf.fr/IMG/mp4/oublier_v_1_1.mp4"},
"rompre (une relation)":{url:"https://www.elix-lsf.fr/IMG/mp4/rompre_v_1_1.mp4"},
"tromper":{url:"https://www.elix-lsf.fr/IMG/mp4/tromper_v_3_1.mp4"},
"fidèle":{url:"https://www.elix-lsf.fr/IMG/mp4/fidele_adj_3_1.mp4"},
"perdre (à un jeu)":{url:"https://www.elix-lsf.fr/IMG/mp4/perdre_v_10_6.mp4"},
"gagner":{url:"https://www.elix-lsf.fr/IMG/mp4/gagner_v_3_1.mp4"},
"une souris":{url:"https://www.elix-lsf.fr/IMG/mp4/00416.mp4"},
"seins":{url:"https://www.elix-lsf.fr/IMG/mp4/seins_nmp_1_6.mp4"},
"poker":{url:"https://www.elix-lsf.fr/IMG/mp4/poker_nm_1_1.mp4"},
"coudre":{url:"https://www.elix-lsf.fr/IMG/mp4/coudre_v_1_1.mp4"},
"tricot":{url:"https://www.elix-lsf.fr/IMG/mp4/tricot.mp4"},
"hélicoptère":{url:"https://www.elix-lsf.fr/IMG/mp4/helicoptere_nm_1_1.mp4"},
"vomir":{url:"https://www.elix-lsf.fr/IMG/mp4/vomir_v_1_1.mp4"},
"allumette":{url:"https://www.elix-lsf.fr/IMG/mp4/allumette_nf_2_1.mp4"},
"tir à l'arc":{url:"https://www.elix-lsf.fr/IMG/mp4/tiralarc_nm_1_1.mp4"},
"aide":{url:"https://www.elix-lsf.fr/IMG/mp4/aide-2.mp4"},
"ou":{url:"https://www.elix-lsf.fr/IMG/mp4/ou.mp4"},
"où":{url:"https://www.elix-lsf.fr/IMG/mp4/ou_adv_1_1.mp4"},
"veuf/veuve":{url:"https://www.elix-lsf.fr/IMG/mp4/veuf_adjetn_1_1.mp4"},
"unique":{url:"https://www.elix-lsf.fr/IMG/mp4/unique_adj_3_1.mp4"},
"la lettre D":{url:"https://www.elix-lsf.fr/IMG/mp4/d_nm_1_1.mp4"},
"grammaire":{url:"https://www.elix-lsf.fr/IMG/mp4/grammaire_nf_1_1.mp4"},
"prêt":{url:"https://www.elix-lsf.fr/IMG/mp4/pret_adj_1_6.mp4"},
"maîtresse":{url:"https://www.elix-lsf.fr/IMG/mp4/maitresse_nf_1_1.mp4"},
"localisation":{url:"https://www.elix-lsf.fr/IMG/mp4/localisation_nf_1_1.mp4"},
"aucun":{url:"https://www.elix-lsf.fr/IMG/mp4/aucun_adj_1_1.mp4"},
"peau":{url:"https://www.elix-lsf.fr/IMG/mp4/peau_nf_1_1.mp4"},
"soleil":{url:"https://www.elix-lsf.fr/IMG/mp4/soleil-3.mp4"},
"naissance":{url:"https://www.elix-lsf.fr/IMG/mp4/naissance.mp4"},
"dernier":{url:"https://www.elix-lsf.fr/IMG/mp4/dernier_adj_1_1.mp4"},
"corde à sauter": {url:"https://www.youtube.com/embed/bxxzZpheLm8"},
"brosse à dents": {url:"https://www.youtube.com/embed/sNJSYGL4d00"},
"boucle d'oreille": {url:"https://www.youtube.com/embed/HwXSp9GjIHE"},
"entendant": {url:"https://www.youtube.com/embed/vsukhDc0anM"},
"nuage":{url:"https://www.elix-lsf.fr/IMG/mp4/nuage_nm_1_1.mp4"},
"pyramide":{url:"https://www.elix-lsf.fr/IMG/mp4/pyramide_nf_1_1.mp4"},
"Égypte":{url:"https://www.elix-lsf.fr/IMG/mp4/egypte_nprop_1_1.mp4"},
"momie":{url:"https://www.elix-lsf.fr/IMG/mp4/momie_nf_1_1.mp4"},
"neige qui tombe":{url:"https://www.elix-lsf.fr/IMG/mp4/neige_nf_1_2.mp4"},
"Cléopâtre":{url:"https://www.elix-lsf.fr/IMG/mp4/cleopatrevii_n_1_6.mp4"},
"hôtesse (de l'air)":{url:"https://www.elix-lsf.fr/IMG/mp4/hotesse_n_1_1.mp4"},
"chien":{url:"https://www.elix-lsf.fr/IMG/mp4/chien_nm_1_6-2.mp4"},
"nom":{url:"https://www.elix-lsf.fr/IMG/mp4/nom_nm_1_1.mp4"},
"Emmanuelle Laborit":{url:"https://www.elix-lsf.fr/IMG/mp4/emmanuellelaborit_nprop_10_6.mp4"},
"Usain Bolt":{url:"https://www.elix-lsf.fr/IMG/mp4/usainbolt_nprop_10_6.mp4"},
"Beyoncé":{url:"https://www.elix-lsf.fr/IMG/mp4/beyonce_nprop_10_6.mp4"},
"Charlie Chaplin":{url:"https://www.elix-lsf.fr/IMG/mp4/charlie_chaplin.mp4"},
"Albert Einstein":{url:"https://www.elix-lsf.fr/IMG/mp4/albert_einstein.mp4"},
"Louis de Funés":{url:"https://www.elix-lsf.fr/IMG/mp4/louisdefunes_n_1_6.mp4"},
"Johnny Haliday":{url:"https://www.elix-lsf.fr/IMG/mp4/johnnyhallyday_nprop_1_6.mp4"},
"Angelina Jolie":{url:"https://www.elix-lsf.fr/IMG/mp4/angelinajolie_nprop_10_6.mp4"},
"Michael Jackson":{url:"https://www.elix-lsf.fr/IMG/mp4/michaeljackson_nprop_10_6.mp4"},
"Madonna":{url:"https://www.elix-lsf.fr/IMG/mp4/madonna_nprop_10_6.mp4"},
"Elvis Presley":{url:"https://www.elix-lsf.fr/IMG/mp4/elvispresley_n_1_6.mp4"},
"Harry Potter":{url:"https://www.elix-lsf.fr/IMG/mp4/harrypotter_nprop_10_6.mp4"},
"Nicolas Sarkozy":{url:"https://www.elix-lsf.fr/IMG/mp4/nicolassarkozy_nprop_1_6.mp4"},
"Tintin":{url:"https://www.elix-lsf.fr/IMG/mp4/tintin_n_1_6.mp4"},
"Spiderman":{url:"https://www.elix-lsf.fr/IMG/mp4/spiderman_nprop_10_6-2.mp4"},
"ballon": {url:"https://www.elix-lsf.fr/IMG/mp4/ballon_nm_2_6-2.mp4"},
"pierre":{url:"https://www.elix-lsf.fr/IMG/mp4/pierre_nf_1_1.mp4"},
"mot":{url:"https://www.elix-lsf.fr/IMG/mp4/mot_nm_1_1.mp4"},
"bavarder":{url:"https://www.elix-lsf.fr/IMG/mp4/bavarder_v_1_1.mp4"},
"porte":{url:"https://www.elix-lsf.fr/IMG/mp4/porte_nf_1_6.mp4"},
"fenêtre":{url:"https://www.elix-lsf.fr/IMG/mp4/fenetre_nf_1_6.mp4"},
"chiffre/nombre":{url:"https://www.elix-lsf.fr/IMG/mp4/chiffre_nm_1_3.mp4"},
"numéro":{url:"https://www.elix-lsf.fr/IMG/mp4/numero_nm_1_6.mp4"},
"poisson":{url:"https://www.elix-lsf.fr/IMG/mp4/poisson_nm_1_6-2.mp4"},
"rivière":{url:"https://www.elix-lsf.fr/IMG/mp4/riviere_nf_1_2.mp4"},
"pont":{url:"https://www.elix-lsf.fr/IMG/mp4/pont_nm_1_1.mp4"},
"moulin":{url:"https://www.elix-lsf.fr/IMG/mp4/moulin_nm_2_1.mp4"},
"électricité":{url:"https://www.elix-lsf.fr/IMG/mp4/electricite_nf_10_6.mp4"},
"immeuble":{url:"https://www.elix-lsf.fr/IMG/mp4/immeuble_adjetn_1_11.mp4"},
"boucher":{url:"https://www.elix-lsf.fr/IMG/mp4/boucher_nm_1_1.mp4"},
"magasin":{url:"https://www.elix-lsf.fr/IMG/mp4/00264.mp4"},
"juif":{url:"https://www.elix-lsf.fr/IMG/mp4/juif_nm_1_6.mp4"},
"Afrique":{url:"https://www.elix-lsf.fr/IMG/mp4/afrique_nprop_1_6.mp4"},
"vent":{url:"https://www.elix-lsf.fr/IMG/mp4/vent_nm_1_6-2.mp4"},
"Europe":{url:"https://www.elix-lsf.fr/IMG/mp4/europe_nprop_1_6.mp4"},
"bibliothèque":{url:"https://www.elix-lsf.fr/IMG/mp4/bibliothe_que.mp4"},
"tableau (de peinture)":{url:"https://www.elix-lsf.fr/IMG/mp4/tableau_nm_4_1.mp4"},
"foin":{url:"https://www.elix-lsf.fr/IMG/mp4/00212.mp4"},
"excrément":{url:"https://www.elix-lsf.fr/IMG/mp4/caca_nm_1_6-2.mp4"},
"chemin":{url:"https://www.elix-lsf.fr/IMG/mp4/chemin_nm_1_1.mp4"},
"étoile":{url:"https://www.elix-lsf.fr/IMG/mp4/etoile_nf_1_1.mp4"},
"bois":{url:"https://www.elix-lsf.fr/IMG/mp4/bois_nm_2_1.mp4"},
"ménage":{url:"https://www.elix-lsf.fr/IMG/mp4/menage_nm_1_1.mp4"},
"carreaux":{url:"https://www.elix-lsf.fr/IMG/mp4/carreau_nm_3_1.mp4"},
"zéro":{url:"https://www.elix-lsf.fr/IMG/mp4/zero_adj_1_1.mp4"},
"un":{url:"https://www.elix-lsf.fr/IMG/mp4/un_adj_3_1.mp4"},
"deux":{url:"https://www.elix-lsf.fr/IMG/mp4/deux_adj_1_1.mp4"},
"trois":{url:"https://www.elix-lsf.fr/IMG/mp4/trois_adjetn_1_1.mp4"},
"quatre":{url:"https://www.elix-lsf.fr/IMG/mp4/quatre_adj_1_1.mp4"},
"cinq":{url:"https://www.elix-lsf.fr/IMG/mp4/cinq_adj_2_1.mp4"},
"six":{url:"https://www.elix-lsf.fr/IMG/mp4/six_adjetn_1_1.mp4"},
"sept":{url:"https://www.elix-lsf.fr/IMG/mp4/sept_nm_1_1.mp4"},
"huit":{url:"https://www.elix-lsf.fr/IMG/mp4/huit_nm_1_1.mp4"},
"neuf":{url:"https://www.elix-lsf.fr/IMG/mp4/neuf_nm_1_1.mp4"},
"dix":{url:"https://www.elix-lsf.fr/IMG/mp4/dix_nm_1_1.mp4"},
"onze":{url:"https://www.elix-lsf.fr/IMG/mp4/onze_adj_1_6.mp4"},
"douze":{url:"https://www.elix-lsf.fr/IMG/mp4/douze_nm_1_1-2.mp4"},
"treize":{url:"https://www.elix-lsf.fr/IMG/mp4/treize-2.mp4"},
"quatorze":{url:"https://www.elix-lsf.fr/IMG/mp4/quatorze_adj_1_1.mp4"},
"quinze":{url:"https://www.elix-lsf.fr/IMG/mp4/quinze_adj_1_1.mp4"},
"seize":{url:"https://www.elix-lsf.fr/IMG/mp4/seize_nm_1_1.mp4"},
"dix-sept":{url:"https://www.elix-lsf.fr/IMG/mp4/dix-sept_adj_1_1.mp4"},
"dix-huit":{url:"https://www.elix-lsf.fr/IMG/mp4/dix-huit_adj_1_1.mp4"},
"dix-neuf":{url:"https://www.elix-lsf.fr/IMG/mp4/dix-neuf_adj_1_1.mp4"},
"vingt":{url:"https://www.elix-lsf.fr/IMG/mp4/vingt_adjetn_1_1.mp4"},
"trente":{url:"https://www.elix-lsf.fr/IMG/mp4/trente_adjetn_1_1.mp4"},
"quarante":{url:"https://www.elix-lsf.fr/IMG/mp4/quarante_adj_1_1.mp4"},
"cinquante":{url:"https://www.elix-lsf.fr/IMG/mp4/cinquante_adj_1_1.mp4"},
"soixante":{url:"https://www.elix-lsf.fr/IMG/mp4/soixante_adjetn_1_1.mp4"},
"soixante-dix":{url:"https://www.elix-lsf.fr/IMG/mp4/soixante-dix_adjetn_1_1.mp4"},
"quatre-vingt":{url:"https://www.elix-lsf.fr/IMG/mp4/quatre-vingt_adj_1_1.mp4"},
"quatre-vingt-dix":{url:"https://www.elix-lsf.fr/IMG/mp4/quatre-vingt-dix_adj_1_1.mp4"},
"cent":{url:"https://www.elix-lsf.fr/IMG/mp4/cent_adj_1_1.mp4"},

"pêcher (à la ligne)":{url:""},
"mode":{url:""},
"vêtement":{url:""},
"bol":{url:""},
"rideaux":{url:""},
"Lady Di – Diana Spencer":{url:""},
"mur":{url:""},
"plante":{url:""},
"phare":{url:""},
"oiseau":{url:""},
"voler":{url:""},
"sphinx":{url:""},
"pharaon":{url:""},
"gauche":{url:""},
"droite":{url:""},
"vocabulaire":{url:""},
"vrai jumeau":{url:""},
"faux jumeau":{url:""},
"défiancer": {url:""},
"PACS": {url:""},
"neige": {url:""},
"ex-": {url:""},
"demi-soeur ": {url:""},
"dent": {url:""},
"menton": {url:""},
"petit": {url:""},
"gourde": {url:""},
"miroir": {url:""},
// "": {url:""},
// "": {url:""},
// "": {url:""},

// "":{url:""},
// "":{url:""},
// bouclé
// tresses
// ondulé
// court
// manga
// Bande dessinée
// Johnny Hallyday
// Canada
// "médicament":{url:""},
// "cowboy":{url:""},
// "pompe à vélo":{url:""},
// "glace a l'italienne":{url:""},
// "glace en baton":{url:""},
// "radio":{url:""},
// "verbe":{url:""},
// "paresseux":{url:""},
// "se présenter":{url:""},
// "teinture":{url:""},
// "tache de rousseur":{url:""},
// "acné":{url:""},
// "grain de beauté":{url:""},
// "célébrité":{url:""},
// "star":{url:"https://www.elix-lsf.fr/IMG/mp4/star_nf_1_1.mp4"},


};

for(let arg in VOCABULARY){
    VOCABULARY[arg].name=arg;
}

LESSONS = {
"Seance 1": {
words: ["signe",
    "bonjour",
    "au revoir",
    "comment ça va ?",
    "être en forme",
    "oui",
    "non",
    "pause",
    "café",
    "thé",
    "être en retard",
    "être fatigué",
    "être malade",
    "s'il vous plaît",
    "pardon",
    "merci",
    "toilettes",
    "sourd",
    "entendant",
    "manger",
    "boire",
    "école",
    "accueil",
    "voiture",
    "eau",
    "boisson",
    "question",
    "signe",
    "avant",
    "maison",
    "sous-titre",
    "télévision",
    "traducteur"
]
},
"Seance 2": {
words: [
    "moto",
    "vélo",
    "scooter",
    "aspirateur",
    "arbre",
    "lampe torche",
    "parapluie",
    "peur",
    "faim",
    "sac à dos",
    "pêcher (à la ligne)",
    "bouteille",
    "soif",
    "avion",
    "fleur",
    "réfrigérateur",
    "congélateur",
    "table",
    "siège",
    "livre",
    "indien d'Amérique",
    "vache",
    "taureau",
    "boiter",
    "chat",
    "une souris",
    "scie",
    "sucette",
    "glace",
    "loupe",
    "bowling",
    "après",
    "partir",
    "hache",
    "peindre",
    "bateau",
    "pluie",
    "douche",
    "violon",
    "dentifrice",
    "brosse à dents",
    "thermomètre",
    "sandwich",
    "hamburger",
    "radin",
    "sèche cheveux ",
    "repasser (le linge)",
    "flûte",
    "trompette",
    "ronfler",
    "carnet",
    "carte à jouer",
    "serrure",
    "clé",
    "savon",
    "photo",
    "image",
    "gourde",
    "puer",
    "sapin",
    "dieu",
    "capricieux",
    "fauteuil",
    "chaise",
    "balai",
    "bâiller",
    "skier",
    "terminer",
    "exemple",
    "poker",
    "coudre",
    "tricot",
    "hélicoptère",
    "vomir",
    "allumette",
    "tir à l'arc",
    "corde à sauter",
    "boucle d'oreille"
]
},
"Seance 3": {
words: ["couleur",
    "bleu",
    "rouge",
    "vert",
    "jaune",
    "gris",
    "rose",
    "noir",
    "blanc",
    "violet",
    "marron",
    "orange",
    "or (métal)",
    "argent (métal)",
    "clair",
    "foncé",
    "vif",
    "transparent",
    "aimer",
    "apprécier",
    "détester",
    "ne pas aimer",
    "compris",
    "pareil",
    "différent",
    "interdit",
    "affiche",
    "écrire",
    "énerver",
    "mer",
    "ciel",
    "quel"
]
},
"Seance 4": {
words: [
    "homme",
    "femme",
    "fille",
    "garçon",
    "jeune",
    "vieux",
    "bébé",
    "grand",
    "petit",
    "mince",
    "maigre",
    "gros",
    "fesses",
    "seins",
    "peau",
    "visage",
    "cheveu",
    "cheveux bouclés",
    "chauve",
    "couettes",
    "blond",
    "roux (cheveux)",
    "brun",
    "bouche",
    "nez",
    "narine",
    "oreille",
    "oeil",
    "langue",
    "sourcil",
    "cils",
    "lèvre",
    "dent",
    "fossette",
    "corps",
    "lunettes",
    "éléphant",
    "enceinte",
    "forme",
    "beau",
    "moche",
    "dessiner",
    "lentille de contact",
    "guitare",
    "travail",
    "facile",
    "difficile"
]
},
"Seance 5": {
words: [
    "noir (de peau)",
    "la joue",
    "nom",
    "Etats-unis",
    "bravo",
    "France",
    "front",
    "théâtre",
    "comédien",
    "président",
    "république",
    "policier",
    "policier",
    "mort",
    "vivant",
    "film",
    "chant",
    "chantsigne",
    "danse",
    "musclé",
    "couronne",
    "roi",
    "prince",
    "caméscope/caméra",
    "cinéma",
    "laid",
    "football",
    "ville",
    "arabe",
    "rap",
    "métis",
    "fusée",
    "aide",
    "Emmanuelle Laborit",
    "Usain Bolt",
    "Beyoncé",
    "Charlie Chaplin",
    "Albert Einstein",
    "Louis de Funés",
    "Johnny Haliday",
    "Angelina Jolie",
    "Michael Jackson",
    "Madonna",
    "Elvis Presley",
    "Harry Potter",
    "Nicolas Sarkozy",
    "Tintin",
    "Spiderman",
    "Lady Di – Diana Spencer"
]
},
"Seance 6": {
words: [
    "vacances",
    "oublier",
    "famille",
    "grands-parents",
    "parents",
    "enfants",
    "grand-mère",
    "grand-père",
    "mère",
    "père",
    "soeur",
    "frère",
    "fille",
    "fils",
    "bébé",
    "petite-fille",
    "petit-fils",
    "nièce",
    "neveu/nièce",
    "cousin/cousine",
    "tante",
    "oncle",
    "gendre",
    "beau-fils",
    "belle-fille",
    "beau-père",
    "belle-mère",
    "arrière grands parents",
    "demi-soeur",
    "demi-frère",
    "amour",
    "couple",
    "petit(e) ami(e)",
    "célibataire",
    "fiancer",
    "marier",
    "PACS",
    "rompre (une relation)",
    "défiancer",
    "divorce",
    "tromper",
    "fidèle",
    "ex-",
    "ami",
    "gay",
    "lesbienne",
    "amant",
    "maitresse ",
    "pêcher (à la ligne)",
    "montagne",
    "campagne",
    "mer",
    "bateau",
    "camping",
    "neige",
    "perdre (à un jeu)",
    "gagner"
]
},
"Seance 7": {
words: [
    "ou",
    "veuf/veuve",
    "unique",
    "aucun",
    "maîtresse",
    "localisation",
    "deux",
    "la lettre D",
    "où",
    "grammaire",
    "prêt",
    "soleil",
    "naissance",
    "dernier",
    "ballon"
    ]
},
"Seance 8": {
words: [
    "mur",
    "plante",
    "nuage",
    "pierre",
    "phare",
    "oiseau",
    "voler",
    "pyramide",
    "sphinx",
    "pharaon",
    "Égypte",
    "gauche",
    "droite",
    "momie",
    "neige qui tombe",
    "Cléopâtre",
    "hôtesse (de l'air)",
    "chien",
    "miroir"
]
},

"Seance 9": {
    words: [
        "porte",
        "fenêtre",
        "chiffre/nombre",
        "numéro",
        "poisson",
        "rivière",
        "pont",
        "moulin",
        "électricité",
        "immeuble",
        "boucher",
        "magasin",
        "mode",
        "vêtement",
        "juif",
        "Afrique",
        "vent",
        "Europe",
        "bibliothèque",
        "tableau (de peinture)",
        "foin",
        "excrément",
        "bol",
        "chemin",
        "étoile",
        "bois",
        "ménage",
        "rideaux",
        "carreaux"
    ]
},
"Seance 10": {
    words: [
        "zéro",
        "un",
        "deux",
        "trois",
        "quatre",
        "cinq",
        "six",
        "sept",
        "huit",
        "neuf",
        "dix",
        "onze",
        "douze",
        "treize",
        "quatorze",
        "quinze",
        "seize",
        "dix-sept",
        "dix-huit",
        "dix-neuf",
        "vingt",
        "trente",
        "quarante",
        "cinquante",
        "soixante",
        "soixante-dix",
        "quatre-vingt",
        "quatre-vingt-dix",
        "cent",
    ]
},

"Seance 11": {
    words: [
        
    ]
},
// "Seance ": {
//     words: [

//     ]
// },

};

CATEGORIES = {
"couleurs": {
words: ["bleu",
    "rouge",
    "vert",
    "jaune",
    "gris",
    "rose",
    "noir",
    "blanc",
    "violet",
    "marron",
    "orange",
    "or (métal)",
    "argent (métal)",
    "clair",
    "foncé",
    "vif",
    "transparent"
]
}
    // "verbe":{]},

};